title: kool Docs
description: An OpenGL / WebGPU engine for Desktop JVM, Android and Javascript written in Kotlin.
theme: just-the-docs

url: https://fabmax.github.io

aux_links:
  kool Templates: https://github.com/fabmax/kool-templates

# External navigation links
nav_external_links:
  - title: kool on GitHub
    url: https://github.com/fabmax/kool

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2017-2024 Max Thiele. Distributed by an <a href=\"https://github.com/fabmax/kool/blob/main/LICENSE\">Apache-2.0 License.</a>"
